from listops import ListDemo
from tupleops import TupleDemo
from dictops import DictDemo
from setops import SetDemo

print("LIST:")
l = ListDemo()
l.display()
l.append_element()
l.insert_element()
l.remove_element()
l.pop_element()
l.reverse_list()
l.sort_list()
l.count_element()
l.index_element()
l.length()

print("\nTUPLE:")
t = TupleDemo()
t.display()
t.count_element()
t.index_element()
t.length()
t.maximum()
t.minimum()

print("\nDICTIONARY: ")
d = DictDemo()
d.display()
d.keys_method()
d.values_method()
d.items_method()
d.get_value()
d.update_value()
d.pop_item()
d.pop_last()

print("\nSET: ")
s = SetDemo()
s.display()
s.add_element()
s.remove_element()
s.discard_element()
s.pop_element()
