from listops import ListDemo
from tupleops import TupleDemo
from dictops import DictDemo
from setops import SetDemo

print("LIST:")
l = ListDemo()
print(l.display())
print(l.append_element())
print(l.insert_element())
print(l.remove_element())
print(l.pop_element())
print(l.reverse_list())
print(l.sort_list())
print(l.count_element())
print(l.index_element())
print(l.length())

print("\nTUPLE:")
t = TupleDemo()
print(t.display())
print(t.count_element())
print(t.index_element())
print(t.length())
print(t.maximum())
print(t.minimum())

print("\nDICTIONARY:")
d = DictDemo()
print(d.display())
print(d.keys_method())
print(d.values_method())
print(d.items_method())
print(d.get_value())
print(d.update_value())
print(d.pop_item())
print(d.pop_last())

print("\nSET:")
s = SetDemo()
print(s.display())
print(s.add_element())
print(s.remove_element())
print(s.discard_element())
print(s.pop_element())